2025-07-15 05:30:08,027 - INFO - app.core.security - LOGIN: user_id=11, email=cursordemo3@gmail.com, user_type=demo, time=2025-07-15T12:30:08.027197
2025-07-15 05:30:56,318 - INFO - app.core.security - LOGOUT: user_id=11, email=cursordemo3@gmail.com, user_type=demo, time=2025-07-15T12:30:56.318548
2025-07-15 05:30:58,717 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-15T12:30:58.717083
2025-07-15 21:10:38,613 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-15 21:10:38,655 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-15 22:56:38,930 - INFO - app.core.security - LOGOUT: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-16T05:56:38.930752
2025-07-15 22:56:44,589 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-16T05:56:44.589355
2025-07-15 23:42:15,159 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-15 23:42:15,177 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 382, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-16 00:20:23,010 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-16T07:20:23.010462
