2025-07-22 03:19:55,117 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:19:55,118 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:21:25,287 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:21:53,547 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:21:53,549 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:23:58,985 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:28:32,205 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:28:32,207 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:30:31,842 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 444, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-22 03:30:31,938 - ERROR - app.core.security - Authentication error in get_user_from_service_or_user_token: Could not validate credentials
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 94, in decode_token
    payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 174, in decode
    _validate_claims(
    ~~~~~~~~~~~~~~~~^
        claims,
        ^^^^^^^
    ...<5 lines>...
        options=defaults,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 497, in _validate_claims
    _validate_exp(claims, leeway=leeway)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\jose\jwt.py", line 331, in _validate_exp
    raise ExpiredSignatureError("Signature has expired.")
jose.exceptions.ExpiredSignatureError: Signature has expired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 444, in get_user_from_service_or_user_token
    payload = decode_token(token)
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 99, in decode_token
    raise JWTError("Could not validate credentials")
jose.exceptions.JWTError: Could not validate credentials
2025-07-22 03:30:41,089 - INFO - app.core.security - LOGOUT: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-22T10:30:41.089650
2025-07-22 03:30:49,033 - INFO - app.core.security - LOGIN: user_id=25, email=huttonsgroups90@gmail.com, user_type=live, time=2025-07-22T10:30:49.033293
2025-07-22 03:31:46,041 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:40:10,230 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:40:10,233 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:40:18,138 - INFO - app.core.security - LOGOUT: user_id=25, email=huttonsgroups90@gmail.com, user_type=live, time=2025-07-22T10:40:18.138574
2025-07-22 03:40:24,606 - INFO - app.core.security - LOGIN: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-22T10:40:24.606644
2025-07-22 03:42:36,131 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 03:54:36,270 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 03:54:36,275 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 03:54:47,333 - INFO - app.core.security - LOGOUT: user_id=30, email=vadoveg221@dosonex.com, user_type=live, time=2025-07-22T10:54:47.333560
2025-07-22 03:54:52,105 - INFO - app.core.security - LOGIN: user_id=1, email=dhanush777ss@gmail.com, user_type=demo, time=2025-07-22T10:54:52.105670
2025-07-22 04:00:24,394 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 21:29:35,630 - ERROR - app.core.security - [Redis] Connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6380, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6380) connecting to localhost:6380.
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 302, in connect_check_health
    await self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect()
    )
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\retry.py", line 71, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 755, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        **self._connection_arguments()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda: protocol, host, port, **kwds)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 1174, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
        ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6380, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6380)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 206, in connect_to_redis
    await client.ping()
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\client.py", line 672, in execute_command
    conn = self.connection or await pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 1141, in get_connection
    await self.ensure_connection(connection)
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 1174, in ensure_connection
    await connection.connect()
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 296, in connect
    await self.connect_check_health(check_health=True)
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 310, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6380, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6380) connecting to localhost:6380.
2025-07-22 21:31:22,593 - ERROR - app.core.security - [Redis] Connection failed: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6380, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6380) connecting to localhost:6380.
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 302, in connect_check_health
    await self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect()
    )
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\retry.py", line 71, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 755, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        **self._connection_arguments()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda: protocol, host, port, **kwds)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 1174, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
        ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6380, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6380)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\core\security.py", line 206, in connect_to_redis
    await client.ping()
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\client.py", line 672, in execute_command
    conn = self.connection or await pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 1141, in get_connection
    await self.ensure_connection(connection)
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 1174, in ensure_connection
    await connection.connect()
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 296, in connect
    await self.connect_check_health(check_health=True)
  File "C:\Users\Dhanush\FASTAPI\venv\Lib\site-packages\redis\asyncio\connection.py", line 310, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6380, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6380) connecting to localhost:6380.
2025-07-22 21:32:50,648 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 21:32:50,652 - WARNING - app.core.security - [Redis] AOF persistence not enabled. Enabling now...
2025-07-22 21:32:50,656 - INFO - app.core.security - [Redis] AOF persistence enabled with appendfsync=everysec.
2025-07-22 21:33:03,620 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-23T04:33:03.619984
2025-07-22 21:36:55,934 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 21:41:56,096 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 21:41:56,100 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 21:43:06,986 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 21:43:09,056 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 21:43:09,057 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 21:43:58,648 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 21:45:32,209 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 21:45:32,212 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 21:46:29,764 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:14:23,493 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:14:23,495 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:14:27,239 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:14:30,044 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:14:30,046 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:14:35,785 - INFO - app.core.security - LOGIN: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T05:14:35.785245
2025-07-22 22:14:49,555 - INFO - app.core.security - LOGOUT: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T05:14:49.555234
2025-07-22 22:14:52,724 - INFO - app.core.security - LOGIN: user_id=1, email=dhanush777ss@gmail.com, user_type=demo, time=2025-07-23T05:14:52.724094
2025-07-22 22:15:16,027 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:29:59,310 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:29:59,312 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:30:11,148 - INFO - app.core.security - LOGOUT: user_id=1, email=dhanush777ss@gmail.com, user_type=demo, time=2025-07-23T05:30:11.148000
2025-07-22 22:30:14,225 - INFO - app.core.security - LOGIN: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T05:30:14.225460
2025-07-22 22:30:42,104 - INFO - app.core.security - LOGOUT: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T05:30:42.104748
2025-07-22 22:30:46,743 - INFO - app.core.security - LOGIN: user_id=1, email=dhanush777ss@gmail.com, user_type=demo, time=2025-07-23T05:30:46.743583
2025-07-22 22:31:25,554 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:32:41,079 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:32:41,081 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:33:38,617 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:37:45,501 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:37:45,502 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:40:10,280 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:42:54,933 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:42:54,934 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:43:15,888 - INFO - app.core.security - LOGOUT: user_id=1, email=dhanush777ss@gmail.com, user_type=demo, time=2025-07-23T05:43:15.888882
2025-07-22 22:43:18,249 - INFO - app.core.security - LOGIN: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T05:43:18.249318
2025-07-22 22:43:37,466 - INFO - app.core.security - LOGOUT: user_id=30, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T05:43:37.466494
2025-07-22 22:43:42,979 - INFO - app.core.security - LOGIN: user_id=14, email=cursordemo3@gmail.com, user_type=live, time=2025-07-23T05:43:42.979595
2025-07-22 22:45:01,407 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:45:09,631 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:45:09,633 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:46:20,873 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:46:23,657 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:46:23,658 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:47:09,325 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-22 22:47:21,602 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-22 22:47:21,604 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-22 22:47:46,270 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 02:21:30,574 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 02:21:30,577 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 02:21:54,587 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-23T09:21:54.587259
2025-07-23 02:24:25,645 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 02:24:28,867 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 02:24:28,869 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 02:27:45,123 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 02:35:40,519 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 02:35:40,522 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 02:36:31,039 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 02:36:57,102 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 02:36:57,104 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 02:38:43,951 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 02:40:45,325 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 02:40:45,329 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 02:44:52,271 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 02:53:27,242 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 02:53:27,245 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 02:54:32,121 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-23T09:54:32.121004
2025-07-23 02:55:47,563 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 03:40:59,581 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 03:40:59,584 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 03:41:16,784 - INFO - app.core.security - LOGIN: user_id=4, email=dhanush777ss@gmail.com, user_type=live, time=2025-07-23T10:41:16.784544
2025-07-23 03:42:34,533 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-23T10:42:34.533349
2025-07-23 03:46:44,163 - INFO - app.core.security - LOGIN: user_id=5, email=livefxhub@gmail.com, user_type=admin, time=2025-07-23T10:46:44.163109
2025-07-23 03:48:48,937 - INFO - app.core.security - [Redis] Connection closed successfully.
2025-07-23 03:48:52,109 - INFO - app.core.security - [Redis] Connected to localhost (127.0.0.1):6380
2025-07-23 03:48:52,112 - INFO - app.core.security - [Redis] AOF persistence already enabled.
2025-07-23 03:49:05,042 - INFO - app.core.security - [Redis] Connection closed successfully.
